nome = input ('Digite o seu nome')
idade = input ('Digite sua idade')
print ('É um prazer te conhecer {} é bom saber que você já tem {} anos'.format(nome, idade))
local = input ('Em que país você nasceu?')
print ('Legal! Eu adoro', local,)