a = input('Digite algo')
print('O tipo primitivo deste valor é:,', type(a))
print('--', a, '-- Tem somente espaços?', a.isspace())
print('--', a, '-- é um número?', a.isnumeric())
print('--', a, '-- é alfabético?', a.isalpha())
print('--', a, '-- é alfanumérico?', a.isalnum())
print('--', a, '-- está todo escrito em maiúsculas?', a.isupper())
print('--', a, '-- está todo escrito em minúsculas?', a.islower())
print('--', a, '-- está capitalizado?', a.istitle())
